/* eslint-disable @typescript-eslint/no-explicit-any */
// TypeScript types corresponding to the Supabase database schema
// This file will eventually be auto-generated by the Supabase CLI,
// but we define it manually here for the initial setup.

export type Json =
    | string
    | number
    | boolean
    | null
    | { [key: string]: Json | undefined }
    | Json[]

export interface Database {
    public: {
        Tables: {
            users: {
                Row: {
                    id: string
                    email: string
                    phone: string | null
                    role: 'user' | 'admin'
                    trust_score: number
                    trust_level: number
                    created_at: string
                    updated_at: string
                }
                Insert: {
                    id: string
                    email: string
                    phone?: string | null
                    role?: 'user' | 'admin'
                    trust_score?: number
                    trust_level?: number
                    created_at?: string
                    updated_at?: string
                }
                Update: {
                    id?: string
                    email?: string
                    phone?: string | null
                    role?: 'user' | 'admin'
                    trust_score?: number
                    trust_level?: number
                    created_at?: string
                    updated_at?: string
                }
            }
            guardians: {
                Row: {
                    id: string
                    user_id: string
                    nickname: string
                    full_name: string | null
                    birth_date: string | null
                    gender: string | null
                    avatar_url: string | null
                    bio: string | null
                    address_name: string | null
                    location: any | null // PostGIS Point
                    verified_region: boolean
                    usage_purpose: ('friend' | 'care' | 'family')[] | null
                    onboarding_progress: number
                    region_verified_at: string | null
                    activity_times: Json
                    preferred_radius_km: number
                    created_at: string
                    updated_at: string
                }
                Insert: {
                    id?: string
                    user_id: string
                    nickname: string
                    full_name?: string | null
                    birth_date?: string | null
                    gender?: string | null
                    avatar_url?: string | null
                    bio?: string | null
                    address_name?: string | null
                    location?: any | null
                    verified_region?: boolean
                    usage_purpose?: ('friend' | 'care' | 'family')[] | null
                    onboarding_progress?: number
                    region_verified_at?: string | null
                    activity_times?: Json
                    preferred_radius_km?: number
                    created_at?: string
                    updated_at?: string
                }
                Update: {
                    id?: string
                    user_id?: string
                    nickname?: string
                    full_name?: string | null
                    birth_date?: string | null
                    gender?: string | null
                    avatar_url?: string | null
                    bio?: string | null
                    address_name?: string | null
                    location?: any | null
                    verified_region?: boolean
                    usage_purpose?: ('friend' | 'care' | 'family')[] | null
                    onboarding_progress?: number
                    region_verified_at?: string | null
                    activity_times?: Json
                    preferred_radius_km?: number
                    created_at?: string
                    updated_at?: string
                }
            }
            dogs: {
                Row: {
                    id: string
                    guardian_id: string
                    name: string
                    breed: string
                    age: number | null
                    birth_date: string | null
                    weight_kg: number | null
                    temperament: Json
                    temperament_profile: Json
                    weekday_walk_slots: ('morning' | 'afternoon' | 'evening')[] | null
                    weekend_walk_slots: ('morning' | 'afternoon' | 'evening')[] | null
                    gender: 'male' | 'female' | null
                    neutered: boolean | null
                    photo_urls: string[] | null
                    vaccination_docs: string[] | null
                    documents: Json | null
                    created_at: string
                    updated_at: string
                }
                Insert: {
                    id?: string
                    guardian_id: string
                    name: string
                    breed: string
                    age?: number | null
                    birth_date?: string | null
                    weight_kg?: number | null
                    temperament?: Json
                    temperament_profile?: Json
                    weekday_walk_slots?: ('morning' | 'afternoon' | 'evening')[] | null
                    weekend_walk_slots?: ('morning' | 'afternoon' | 'evening')[] | null
                    gender?: 'male' | 'female' | null
                    neutered?: boolean | null
                    photo_urls?: string[] | null
                    vaccination_docs?: string[] | null
                    documents?: Json | null
                    created_at?: string
                    updated_at?: string
                }
                Update: {
                    id?: string
                    guardian_id?: string
                    name?: string
                    breed?: string
                    age?: number | null
                    birth_date?: string | null
                    weight_kg?: number | null
                    temperament?: Json
                    temperament_profile?: Json
                    weekday_walk_slots?: ('morning' | 'afternoon' | 'evening')[] | null
                    weekend_walk_slots?: ('morning' | 'afternoon' | 'evening')[] | null
                    gender?: 'male' | 'female' | null
                    neutered?: boolean | null
                    photo_urls?: string[] | null
                    vaccination_docs?: string[] | null
                    documents?: Json | null
                    created_at?: string
                    updated_at?: string
                }
            }
            matches: {
                Row: {
                    id: string
                    from_guardian_id: string
                    to_guardian_id: string
                    status: 'pending' | 'accepted' | 'rejected'
                    relation_purpose: 'friend' | 'care' | 'family' | null
                    liked_section: string | null
                    comment: string | null
                    intro_message: string | null
                    quick_message_code: string | null
                    compatibility_score: number | null
                    created_at: string
                    updated_at: string
                }
                Insert: {
                    id?: string
                    from_guardian_id: string
                    to_guardian_id: string
                    status?: 'pending' | 'accepted' | 'rejected'
                    relation_purpose?: 'friend' | 'care' | 'family' | null
                    liked_section?: string | null
                    comment?: string | null
                    intro_message?: string | null
                    quick_message_code?: string | null
                    compatibility_score?: number | null
                    created_at?: string
                    updated_at?: string
                }
                Update: {
                    id?: string
                    from_guardian_id?: string
                    to_guardian_id?: string
                    status?: 'pending' | 'accepted' | 'rejected'
                    relation_purpose?: 'friend' | 'care' | 'family' | null
                    liked_section?: string | null
                    comment?: string | null
                    intro_message?: string | null
                    quick_message_code?: string | null
                    compatibility_score?: number | null
                    created_at?: string
                    updated_at?: string
                }
            }
            blocks: {
                Row: {
                    id: string
                    blocker_id: string
                    blocked_id: string
                    reason: string | null
                    created_at: string
                }
                Insert: {
                    id?: string
                    blocker_id: string
                    blocked_id: string
                    reason?: string | null
                    created_at?: string
                }
                Update: {
                    id?: string
                    blocker_id?: string
                    blocked_id?: string
                    reason?: string | null
                    created_at?: string
                }
            }
            chat_rooms: {
                Row: {
                    id: string
                    type: 'direct' | 'group'
                    last_message_at: string | null
                    created_at: string
                }
                Insert: {
                    id?: string
                    type?: 'direct' | 'group'
                    last_message_at?: string | null
                    created_at?: string
                }
                Update: {
                    id?: string
                    type?: 'direct' | 'group'
                    last_message_at?: string | null
                    created_at?: string
                }
            }
            chat_participants: {
                Row: {
                    room_id: string
                    guardian_id: string
                    joined_at: string
                }
                Insert: {
                    room_id: string
                    guardian_id: string
                    joined_at?: string
                }
                Update: {
                    room_id?: string
                    guardian_id?: string
                    joined_at?: string
                }
            }
            chat_messages: {
                Row: {
                    id: string
                    room_id: string
                    sender_id: string | null
                    type: 'text' | 'image' | 'schedule' | 'system'
                    content: string | null
                    metadata: Json | null
                    read_by: string[] | null
                    created_at: string
                }
                Insert: {
                    id?: string
                    room_id: string
                    sender_id?: string | null
                    type?: 'text' | 'image' | 'schedule' | 'system'
                    content?: string | null
                    metadata?: Json | null
                    read_by?: string[] | null
                    created_at?: string
                }
                Update: {
                    id?: string
                    room_id?: string
                    sender_id?: string | null
                    type?: 'text' | 'image' | 'schedule' | 'system'
                    content?: string | null
                    metadata?: Json | null
                    read_by?: string[] | null
                    created_at?: string
                }
            }
            schedules: {
                Row: {
                    id: string
                    room_id: string
                    organizer_id: string
                    title: string
                    location_name: string | null
                    location_geog: any | null
                    place_detail: string | null
                    datetime: string
                    status: 'proposed' | 'confirmed' | 'completed' | 'cancelled'
                    proposal_status: 'proposed' | 'accepted' | 'rejected' | 'expired' | null
                    confirmed_at: string | null
                    participant_ids: string[]
                    created_at: string
                    updated_at: string
                }
                Insert: {
                    id?: string
                    room_id: string
                    organizer_id: string
                    title: string
                    location_name?: string | null
                    location_geog?: any | null
                    place_detail?: string | null
                    datetime: string
                    status?: 'proposed' | 'confirmed' | 'completed' | 'cancelled'
                    proposal_status?: 'proposed' | 'accepted' | 'rejected' | 'expired' | null
                    confirmed_at?: string | null
                    participant_ids: string[]
                    created_at?: string
                    updated_at?: string
                }
                Update: {
                    id?: string
                    room_id?: string
                    organizer_id?: string
                    title?: string
                    location_name?: string | null
                    location_geog?: any | null
                    place_detail?: string | null
                    datetime?: string
                    status?: 'proposed' | 'confirmed' | 'completed' | 'cancelled'
                    proposal_status?: 'proposed' | 'accepted' | 'rejected' | 'expired' | null
                    confirmed_at?: string | null
                    participant_ids?: string[]
                    created_at?: string
                    updated_at?: string
                }
            }
            danglogs: {
                Row: {
                    id: string
                    author_id: string
                    dog_id: string | null
                    title: string | null
                    content: string
                    image_urls: string[] | null
                    activity_type: string | null
                    shared_with: string[] | null
                    co_authors: string[] | null
                    created_at: string
                    updated_at: string
                }
                Insert: {
                    id?: string
                    author_id: string
                    dog_id?: string | null
                    title?: string | null
                    content: string
                    image_urls?: string[] | null
                    activity_type?: string | null
                    shared_with?: string[] | null
                    co_authors?: string[] | null
                    created_at?: string
                    updated_at?: string
                }
                Update: {
                    id?: string
                    author_id?: string
                    dog_id?: string | null
                    title?: string | null
                    content?: string
                    image_urls?: string[] | null
                    activity_type?: string | null
                    shared_with?: string[] | null
                    co_authors?: string[] | null
                    created_at?: string
                    updated_at?: string
                }
            }
            danglog_comments: {
                Row: {
                    id: string
                    danglog_id: string
                    author_id: string
                    content: string
                    created_at: string
                    updated_at: string
                }
                Insert: {
                    id?: string
                    danglog_id: string
                    author_id: string
                    content: string
                    created_at?: string
                    updated_at?: string
                }
                Update: {
                    id?: string
                    danglog_id?: string
                    author_id?: string
                    content?: string
                    created_at?: string
                    updated_at?: string
                }
            }
            danglog_likes: {
                Row: {
                    danglog_id: string
                    guardian_id: string
                    created_at: string
                }
                Insert: {
                    danglog_id: string
                    guardian_id: string
                    created_at?: string
                }
                Update: {
                    danglog_id?: string
                    guardian_id?: string
                    created_at?: string
                }
            }
            reviews: {
                Row: {
                    id: string
                    author_id: string
                    target_id: string
                    schedule_id: string | null
                    rating: number
                    content: string | null
                    tags: string[] | null
                    created_at: string
                }
                Insert: {
                    id?: string
                    author_id: string
                    target_id: string
                    schedule_id?: string | null
                    rating: number
                    content?: string | null
                    tags?: string[] | null
                    created_at?: string
                }
                Update: {
                    id?: string
                    author_id?: string
                    target_id?: string
                    schedule_id?: string | null
                    rating?: number
                    content?: string | null
                    tags?: string[] | null
                    created_at?: string
                }
            }
            trust_badges: {
                Row: {
                    id: string
                    guardian_id: string
                    badge_type: 'verified' | 'active_walker' | 'top_reviewer' | 'care_angel'
                    earned_at: string
                }
                Insert: {
                    id?: string
                    guardian_id: string
                    badge_type: 'verified' | 'active_walker' | 'top_reviewer' | 'care_angel'
                    earned_at?: string
                }
                Update: {
                    id?: string
                    guardian_id?: string
                    badge_type?: 'verified' | 'active_walker' | 'top_reviewer' | 'care_angel'
                    earned_at?: string
                }
            }
            notifications: {
                Row: {
                    id: string
                    user_id: string
                    type: string
                    title: string
                    body: string
                    data_json: Json | null
                    read_at: string | null
                    created_at: string
                }
                Insert: {
                    id?: string
                    user_id: string
                    type: string
                    title: string
                    body: string
                    data_json?: Json | null
                    read_at?: string | null
                    created_at?: string
                }
                Update: {
                    id?: string
                    user_id?: string
                    type?: string
                    title?: string
                    body?: string
                    data_json?: Json | null
                    read_at?: string | null
                    created_at?: string
                }
            }
            walk_records: {
                Row: {
                    id: string
                    schedule_id: string | null
                    author_id: string
                    partner_guardian_id: string | null
                    walk_date: string
                    walk_time: string | null
                    place_name: string | null
                    memo: string | null
                    photo_urls: string[] | null
                    visibility: 'public' | 'neighbor' | 'private'
                    created_at: string
                    updated_at: string
                }
                Insert: {
                    id?: string
                    schedule_id?: string | null
                    author_id: string
                    partner_guardian_id?: string | null
                    walk_date?: string
                    walk_time?: string | null
                    place_name?: string | null
                    memo?: string | null
                    photo_urls?: string[] | null
                    visibility?: 'public' | 'neighbor' | 'private'
                    created_at?: string
                    updated_at?: string
                }
                Update: {
                    id?: string
                    schedule_id?: string | null
                    author_id?: string
                    partner_guardian_id?: string | null
                    walk_date?: string
                    walk_time?: string | null
                    place_name?: string | null
                    memo?: string | null
                    photo_urls?: string[] | null
                    visibility?: 'public' | 'neighbor' | 'private'
                    created_at?: string
                    updated_at?: string
                }
            }
            walk_reviews: {
                Row: {
                    id: string
                    walk_record_id: string | null
                    schedule_id: string | null
                    author_id: string
                    target_id: string
                    rating: number
                    comment: string | null
                    visibility: 'public' | 'neighbor' | 'private'
                    created_at: string
                }
                Insert: {
                    id?: string
                    walk_record_id?: string | null
                    schedule_id?: string | null
                    author_id: string
                    target_id: string
                    rating: number
                    comment?: string | null
                    visibility?: 'public' | 'neighbor' | 'private'
                    created_at?: string
                }
                Update: {
                    id?: string
                    walk_record_id?: string | null
                    schedule_id?: string | null
                    author_id?: string
                    target_id?: string
                    rating?: number
                    comment?: string | null
                    visibility?: 'public' | 'neighbor' | 'private'
                    created_at?: string
                }
            }
            danglog_collaborators: {
                Row: {
                    danglog_id: string
                    guardian_id: string
                    role: 'owner' | 'editor' | 'viewer'
                    invited_by: string | null
                    joined_at: string
                }
                Insert: {
                    danglog_id: string
                    guardian_id: string
                    role?: 'owner' | 'editor' | 'viewer'
                    invited_by?: string | null
                    joined_at?: string
                }
                Update: {
                    danglog_id?: string
                    guardian_id?: string
                    role?: 'owner' | 'editor' | 'viewer'
                    invited_by?: string | null
                    joined_at?: string
                }
            }
            danglog_invites: {
                Row: {
                    id: string
                    danglog_id: string
                    invited_by: string
                    invite_token: string
                    status: 'pending' | 'accepted' | 'expired' | 'revoked'
                    expires_at: string | null
                    created_at: string
                }
                Insert: {
                    id?: string
                    danglog_id: string
                    invited_by: string
                    invite_token: string
                    status?: 'pending' | 'accepted' | 'expired' | 'revoked'
                    expires_at?: string | null
                    created_at?: string
                }
                Update: {
                    id?: string
                    danglog_id?: string
                    invited_by?: string
                    invite_token?: string
                    status?: 'pending' | 'accepted' | 'expired' | 'revoked'
                    expires_at?: string | null
                    created_at?: string
                }
            }
            notification_settings: {
                Row: {
                    user_id: string
                    marketing_opt_in: boolean
                    chat_opt_in: boolean
                    schedule_opt_in: boolean
                    danglog_opt_in: boolean
                    push_opt_in: boolean
                    updated_at: string
                }
                Insert: {
                    user_id: string
                    marketing_opt_in?: boolean
                    chat_opt_in?: boolean
                    schedule_opt_in?: boolean
                    danglog_opt_in?: boolean
                    push_opt_in?: boolean
                    updated_at?: string
                }
                Update: {
                    user_id?: string
                    marketing_opt_in?: boolean
                    chat_opt_in?: boolean
                    schedule_opt_in?: boolean
                    danglog_opt_in?: boolean
                    push_opt_in?: boolean
                    updated_at?: string
                }
            }
            consent_logs: {
                Row: {
                    id: string
                    user_id: string
                    consent_type: 'privacy' | 'marketing' | 'location' | 'terms'
                    consented: boolean
                    policy_version: string
                    metadata: Json
                    created_at: string
                }
                Insert: {
                    id?: string
                    user_id: string
                    consent_type: 'privacy' | 'marketing' | 'location' | 'terms'
                    consented: boolean
                    policy_version: string
                    metadata?: Json
                    created_at?: string
                }
                Update: {
                    id?: string
                    user_id?: string
                    consent_type?: 'privacy' | 'marketing' | 'location' | 'terms'
                    consented?: boolean
                    policy_version?: string
                    metadata?: Json
                    created_at?: string
                }
            }
            care_requests: {
                Row: {
                    id: string
                    requester_id: string
                    caregiver_id: string
                    dog_id: string | null
                    title: string
                    description: string | null
                    care_type: 'walk' | 'sitting' | 'grooming' | 'hospital' | 'other'
                    datetime: string
                    duration_hours: number
                    status: 'pending' | 'accepted' | 'completed' | 'cancelled'
                    created_at: string
                    updated_at: string
                }
                Insert: {
                    id?: string
                    requester_id: string
                    caregiver_id: string
                    dog_id?: string | null
                    title: string
                    description?: string | null
                    care_type: 'walk' | 'sitting' | 'grooming' | 'hospital' | 'other'
                    datetime: string
                    duration_hours?: number
                    status?: 'pending' | 'accepted' | 'completed' | 'cancelled'
                    created_at?: string
                    updated_at?: string
                }
                Update: {
                    id?: string
                    requester_id?: string
                    caregiver_id?: string
                    dog_id?: string | null
                    title?: string
                    description?: string | null
                    care_type?: 'walk' | 'sitting' | 'grooming' | 'hospital' | 'other'
                    datetime?: string
                    duration_hours?: number
                    status?: 'pending' | 'accepted' | 'completed' | 'cancelled'
                    created_at?: string
                    updated_at?: string
                }
            }
            family_groups: {
                Row: {
                    id: string
                    name: string
                    creator_id: string
                    dog_ids: string[]
                    created_at: string
                }
                Insert: {
                    id?: string
                    name: string
                    creator_id: string
                    dog_ids?: string[]
                    created_at?: string
                }
                Update: {
                    id?: string
                    name?: string
                    creator_id?: string
                    dog_ids?: string[]
                    created_at?: string
                }
            }
            family_members: {
                Row: {
                    group_id: string
                    member_id: string
                    role: 'owner' | 'admin' | 'member'
                    joined_at: string
                }
                Insert: {
                    group_id: string
                    member_id: string
                    role?: 'owner' | 'admin' | 'member'
                    joined_at?: string
                }
                Update: {
                    group_id?: string
                    member_id?: string
                    role?: 'owner' | 'admin' | 'member'
                    joined_at?: string
                }
            }
            mode_unlocks: {
                Row: {
                    id: string
                    guardian_id: string
                    mode: 'basic' | 'care' | 'family'
                    unlocked_at: string
                    criteria_met_json: Json
                }
                Insert: {
                    id?: string
                    guardian_id: string
                    mode: 'basic' | 'care' | 'family'
                    unlocked_at?: string
                    criteria_met_json: Json
                }
                Update: {
                    id?: string
                    guardian_id?: string
                    mode?: 'basic' | 'care' | 'family'
                    unlocked_at?: string
                    criteria_met_json?: Json
                }
            }
            partner_places: {
                Row: {
                    id: string
                    name: string
                    category: string
                    address_name: string | null
                    location: any | null
                    description: string | null
                    photo_urls: string[]
                    business_hours: Json | null
                    is_verified: boolean
                    amenities: string[]
                    created_at: string
                    updated_at: string
                }
                Insert: {
                    id?: string
                    name: string
                    category: string
                    address_name?: string | null
                    location?: any | null
                    description?: string | null
                    photo_urls?: string[]
                    business_hours?: Json | null
                    is_verified?: boolean
                    amenities?: string[]
                    created_at?: string
                    updated_at?: string
                }
                Update: {
                    id?: string
                    name?: string
                    category?: string
                    address_name?: string | null
                    location?: any | null
                    description?: string | null
                    photo_urls?: string[]
                    business_hours?: Json | null
                    is_verified?: boolean
                    amenities?: string[]
                    created_at?: string
                    updated_at?: string
                }
            }
            reservations: {
                Row: {
                    id: string
                    place_id: string
                    guardian_id: string
                    dog_id: string | null
                    reserved_at: string
                    status: 'pending' | 'confirmed' | 'completed' | 'cancelled'
                    guest_count: number
                    request_memo: string | null
                    created_at: string
                }
                Insert: {
                    id?: string
                    place_id: string
                    guardian_id: string
                    dog_id?: string | null
                    reserved_at: string
                    status?: 'pending' | 'confirmed' | 'completed' | 'cancelled'
                    guest_count?: number
                    request_memo?: string | null
                    created_at?: string
                }
                Update: {
                    id?: string
                    place_id?: string
                    guardian_id?: string
                    dog_id?: string | null
                    reserved_at?: string
                    status?: 'pending' | 'confirmed' | 'completed' | 'cancelled'
                    guest_count?: number
                    request_memo?: string | null
                    created_at?: string
                }
            }
            reports: {
                Row: {
                    id: string
                    reporter_id: string | null
                    target_guardian_id: string
                    reason_category: string
                    content: string | null
                    evidence_urls: string[]
                    status: 'pending' | 'reviewing' | 'resolved' | 'dismissed'
                    admin_memo: string | null
                    created_at: string
                }
                Insert: {
                    id?: string
                    reporter_id?: string | null
                    target_guardian_id: string
                    reason_category: string
                    content?: string | null
                    evidence_urls?: string[]
                    status?: 'pending' | 'reviewing' | 'resolved' | 'dismissed'
                    admin_memo?: string | null
                    created_at?: string
                }
                Update: {
                    id?: string
                    reporter_id?: string | null
                    target_guardian_id?: string
                    reason_category?: string
                    content?: string | null
                    evidence_urls?: string[]
                    status?: 'pending' | 'reviewing' | 'resolved' | 'dismissed'
                    admin_memo?: string | null
                    created_at?: string
                }
            }
            dog_ownership: {
                Row: {
                    dog_id: string
                    guardian_id: string
                    role: 'owner' | 'co_owner' | 'sitter'
                    is_primary: boolean
                    created_at: string
                }
                Insert: {
                    dog_id: string
                    guardian_id: string
                    role?: 'owner' | 'co_owner' | 'sitter'
                    is_primary?: boolean
                    created_at?: string
                }
                Update: {
                    dog_id?: string
                    guardian_id?: string
                    role?: 'owner' | 'co_owner' | 'sitter'
                    is_primary?: boolean
                    created_at?: string
                }
            }
            schedule_participants: {
                Row: {
                    schedule_id: string
                    guardian_id: string
                    dog_id: string | null
                    status: 'invited' | 'accepted' | 'declined'
                    joined_at: string
                }
                Insert: {
                    schedule_id: string
                    guardian_id: string
                    dog_id?: string | null
                    status?: 'invited' | 'accepted' | 'declined'
                    joined_at?: string
                }
                Update: {
                    schedule_id?: string
                    guardian_id?: string
                    dog_id?: string | null
                    status?: 'invited' | 'accepted' | 'declined'
                    joined_at?: string
                }
            }
        }
        Views: {
            [_ in never]: never
        }
        Functions: {
            match_guardians_v2: {
                Args: {
                    p_guardian_id: string
                    p_mode?: 'basic' | 'care' | 'family'
                    p_limit?: number
                    p_offset?: number
                }
                Returns: {
                    target_guardian_id: string
                    distance_meters: number
                    time_overlap_score: number
                    compatibility_score: number
                    is_verified: boolean
                }[]
            }
            create_chat_room_with_participants: {
                Args: {
                    p_my_guardian_id: string
                    p_partner_guardian_id: string
                }
                Returns: string
            }
            set_guardian_location: {
                Args: {
                    p_guardian_id: string
                    p_lng: number
                    p_lat: number
                }
                Returns: undefined
            }
        }
        Enums: {
            user_role: 'user' | 'admin'
            match_status: 'pending' | 'accepted' | 'rejected'
            schedule_status: 'proposed' | 'confirmed' | 'completed' | 'cancelled'
            chat_room_type: 'direct' | 'group'
            message_type: 'text' | 'image' | 'schedule' | 'system'
            dog_gender: 'male' | 'female'
            badge_type: 'verified' | 'active_walker' | 'top_reviewer' | 'care_angel'
            mode_type: 'basic' | 'care' | 'family'
            relation_purpose: 'friend' | 'care' | 'family'
            visibility_scope: 'public' | 'neighbor' | 'private'
            time_slot: 'morning' | 'afternoon' | 'evening'
            dog_trait_scale: 'low' | 'mid' | 'high'
            care_type: 'walk' | 'sitting' | 'grooming' | 'hospital' | 'other'
            care_status: 'pending' | 'accepted' | 'completed' | 'cancelled'
            family_role: 'owner' | 'admin' | 'member'
            profile_visibility: 'public' | 'neighbor' | 'private'
            place_category: 'cafe' | 'hospital' | 'salon' | 'park'
            reservation_status: 'pending' | 'confirmed' | 'completed' | 'cancelled'
            report_status: 'pending' | 'reviewing' | 'resolved' | 'dismissed'
            dog_ownership_role: 'owner' | 'co_owner' | 'sitter'
            schedule_participant_status: 'invited' | 'accepted' | 'declined'
        }
        CompositeTypes: {
            [_ in never]: never
        }
    }
}
