/* eslint-disable @typescript-eslint/no-explicit-any */
// TypeScript types corresponding to the Supabase database schema
// This file will eventually be auto-generated by the Supabase CLI,
// but we define it manually here for the initial setup.

export type Json =
    | string
    | number
    | boolean
    | null
    | { [key: string]: Json | undefined }
    | Json[]

export interface Database {
    public: {
        Tables: {
            users: {
                Row: {
                    id: string
                    email: string
                    phone: string | null
                    role: 'user' | 'admin'
                    trust_score: number
                    trust_level: number
                    created_at: string
                    updated_at: string
                }
                Insert: {
                    id: string
                    email: string
                    phone?: string | null
                    role?: 'user' | 'admin'
                    trust_score?: number
                    trust_level?: number
                    created_at?: string
                    updated_at?: string
                }
                Update: {
                    id?: string
                    email?: string
                    phone?: string | null
                    role?: 'user' | 'admin'
                    trust_score?: number
                    trust_level?: number
                    created_at?: string
                    updated_at?: string
                }
            }
            guardians: {
                Row: {
                    id: string
                    user_id: string
                    nickname: string
                    avatar_url: string | null
                    bio: string | null
                    address_name: string | null
                    location: any | null // PostGIS Point
                    verified_region: boolean
                    activity_times: Json
                    preferred_radius_km: number
                    created_at: string
                    updated_at: string
                }
                Insert: {
                    id?: string
                    user_id: string
                    nickname: string
                    avatar_url?: string | null
                    bio?: string | null
                    address_name?: string | null
                    location?: any | null
                    verified_region?: boolean
                    activity_times?: Json
                    preferred_radius_km?: number
                    created_at?: string
                    updated_at?: string
                }
                Update: {
                    id?: string
                    user_id?: string
                    nickname?: string
                    avatar_url?: string | null
                    bio?: string | null
                    address_name?: string | null
                    location?: any | null
                    verified_region?: boolean
                    activity_times?: Json
                    preferred_radius_km?: number
                    created_at?: string
                    updated_at?: string
                }
            }
            dogs: {
                Row: {
                    id: string
                    guardian_id: string
                    name: string
                    breed: string
                    age: number | null
                    weight_kg: number | null
                    temperament: Json
                    gender: 'male' | 'female' | null
                    neutered: boolean | null
                    photo_urls: string[] | null
                    vaccination_docs: string[] | null
                    created_at: string
                    updated_at: string
                }
                Insert: {
                    id?: string
                    guardian_id: string
                    name: string
                    breed: string
                    age?: number | null
                    weight_kg?: number | null
                    temperament?: Json
                    gender?: 'male' | 'female' | null
                    neutered?: boolean | null
                    photo_urls?: string[] | null
                    vaccination_docs?: string[] | null
                    created_at?: string
                    updated_at?: string
                }
                Update: {
                    id?: string
                    guardian_id?: string
                    name?: string
                    breed?: string
                    age?: number | null
                    weight_kg?: number | null
                    temperament?: Json
                    gender?: 'male' | 'female' | null
                    neutered?: boolean | null
                    photo_urls?: string[] | null
                    vaccination_docs?: string[] | null
                    created_at?: string
                    updated_at?: string
                }
            }
            matches: {
                Row: {
                    id: string
                    from_guardian_id: string
                    to_guardian_id: string
                    status: 'pending' | 'accepted' | 'rejected'
                    liked_section: string | null
                    comment: string | null
                    compatibility_score: number | null
                    created_at: string
                    updated_at: string
                }
                Insert: {
                    id?: string
                    from_guardian_id: string
                    to_guardian_id: string
                    status?: 'pending' | 'accepted' | 'rejected'
                    liked_section?: string | null
                    comment?: string | null
                    compatibility_score?: number | null
                    created_at?: string
                    updated_at?: string
                }
                Update: {
                    id?: string
                    from_guardian_id?: string
                    to_guardian_id?: string
                    status?: 'pending' | 'accepted' | 'rejected'
                    liked_section?: string | null
                    comment?: string | null
                    compatibility_score?: number | null
                    created_at?: string
                    updated_at?: string
                }
            }
            blocks: {
                Row: {
                    id: string
                    blocker_id: string
                    blocked_id: string
                    reason: string | null
                    created_at: string
                }
                Insert: {
                    id?: string
                    blocker_id: string
                    blocked_id: string
                    reason?: string | null
                    created_at?: string
                }
                Update: {
                    id?: string
                    blocker_id?: string
                    blocked_id?: string
                    reason?: string | null
                    created_at?: string
                }
            }
            chat_rooms: {
                Row: {
                    id: string
                    type: 'direct' | 'group'
                    last_message_at: string | null
                    created_at: string
                }
                Insert: {
                    id?: string
                    type?: 'direct' | 'group'
                    last_message_at?: string | null
                    created_at?: string
                }
                Update: {
                    id?: string
                    type?: 'direct' | 'group'
                    last_message_at?: string | null
                    created_at?: string
                }
            }
            chat_participants: {
                Row: {
                    room_id: string
                    guardian_id: string
                    joined_at: string
                }
                Insert: {
                    room_id: string
                    guardian_id: string
                    joined_at?: string
                }
                Update: {
                    room_id?: string
                    guardian_id?: string
                    joined_at?: string
                }
            }
            chat_messages: {
                Row: {
                    id: string
                    room_id: string
                    sender_id: string | null
                    type: 'text' | 'image' | 'schedule' | 'system'
                    content: string | null
                    metadata: Json | null
                    read_by: string[] | null
                    created_at: string
                }
                Insert: {
                    id?: string
                    room_id: string
                    sender_id?: string | null
                    type?: 'text' | 'image' | 'schedule' | 'system'
                    content?: string | null
                    metadata?: Json | null
                    read_by?: string[] | null
                    created_at?: string
                }
                Update: {
                    id?: string
                    room_id?: string
                    sender_id?: string | null
                    type?: 'text' | 'image' | 'schedule' | 'system'
                    content?: string | null
                    metadata?: Json | null
                    read_by?: string[] | null
                    created_at?: string
                }
            }
            schedules: {
                Row: {
                    id: string
                    room_id: string
                    organizer_id: string
                    title: string
                    location_name: string | null
                    location_geog: any | null
                    datetime: string
                    status: 'proposed' | 'confirmed' | 'completed' | 'cancelled'
                    participant_ids: string[]
                    created_at: string
                    updated_at: string
                }
                Insert: {
                    id?: string
                    room_id: string
                    organizer_id: string
                    title: string
                    location_name?: string | null
                    location_geog?: any | null
                    datetime: string
                    status?: 'proposed' | 'confirmed' | 'completed' | 'cancelled'
                    participant_ids: string[]
                    created_at?: string
                    updated_at?: string
                }
                Update: {
                    id?: string
                    room_id?: string
                    organizer_id?: string
                    title?: string
                    location_name?: string | null
                    location_geog?: any | null
                    datetime?: string
                    status?: 'proposed' | 'confirmed' | 'completed' | 'cancelled'
                    participant_ids?: string[]
                    created_at?: string
                    updated_at?: string
                }
            }
            danglogs: {
                Row: {
                    id: string
                    author_id: string
                    dog_id: string | null
                    title: string | null
                    content: string
                    image_urls: string[] | null
                    activity_type: string | null
                    shared_with: string[] | null
                    co_authors: string[] | null
                    created_at: string
                    updated_at: string
                }
                Insert: {
                    id?: string
                    author_id: string
                    dog_id?: string | null
                    title?: string | null
                    content: string
                    image_urls?: string[] | null
                    activity_type?: string | null
                    shared_with?: string[] | null
                    co_authors?: string[] | null
                    created_at?: string
                    updated_at?: string
                }
                Update: {
                    id?: string
                    author_id?: string
                    dog_id?: string | null
                    title?: string | null
                    content?: string
                    image_urls?: string[] | null
                    activity_type?: string | null
                    shared_with?: string[] | null
                    co_authors?: string[] | null
                    created_at?: string
                    updated_at?: string
                }
            }
            danglog_comments: {
                Row: {
                    id: string
                    danglog_id: string
                    author_id: string
                    content: string
                    created_at: string
                    updated_at: string
                }
                Insert: {
                    id?: string
                    danglog_id: string
                    author_id: string
                    content: string
                    created_at?: string
                    updated_at?: string
                }
                Update: {
                    id?: string
                    danglog_id?: string
                    author_id?: string
                    content?: string
                    created_at?: string
                    updated_at?: string
                }
            }
            danglog_likes: {
                Row: {
                    danglog_id: string
                    guardian_id: string
                    created_at: string
                }
                Insert: {
                    danglog_id: string
                    guardian_id: string
                    created_at?: string
                }
                Update: {
                    danglog_id?: string
                    guardian_id?: string
                    created_at?: string
                }
            }
            reviews: {
                Row: {
                    id: string
                    author_id: string
                    target_id: string
                    schedule_id: string | null
                    rating: number
                    content: string | null
                    tags: string[] | null
                    created_at: string
                }
                Insert: {
                    id?: string
                    author_id: string
                    target_id: string
                    schedule_id?: string | null
                    rating: number
                    content?: string | null
                    tags?: string[] | null
                    created_at?: string
                }
                Update: {
                    id?: string
                    author_id?: string
                    target_id?: string
                    schedule_id?: string | null
                    rating?: number
                    content?: string | null
                    tags?: string[] | null
                    created_at?: string
                }
            }
            trust_badges: {
                Row: {
                    id: string
                    guardian_id: string
                    badge_type: 'verified' | 'active_walker' | 'top_reviewer' | 'care_angel'
                    earned_at: string
                }
                Insert: {
                    id?: string
                    guardian_id: string
                    badge_type: 'verified' | 'active_walker' | 'top_reviewer' | 'care_angel'
                    earned_at?: string
                }
                Update: {
                    id?: string
                    guardian_id?: string
                    badge_type?: 'verified' | 'active_walker' | 'top_reviewer' | 'care_angel'
                    earned_at?: string
                }
            }
            notifications: {
                Row: {
                    id: string
                    user_id: string
                    type: string
                    title: string
                    body: string
                    data_json: Json | null
                    read_at: string | null
                    created_at: string
                }
                Insert: {
                    id?: string
                    user_id: string
                    type: string
                    title: string
                    body: string
                    data_json?: Json | null
                    read_at?: string | null
                    created_at?: string
                }
                Update: {
                    id?: string
                    user_id?: string
                    type?: string
                    title?: string
                    body?: string
                    data_json?: Json | null
                    read_at?: string | null
                    created_at?: string
                }
            }
            care_requests: {
                Row: {
                    id: string
                    requester_id: string
                    caregiver_id: string
                    dog_id: string | null
                    title: string
                    description: string | null
                    care_type: 'walk' | 'sitting' | 'grooming' | 'hospital' | 'other'
                    datetime: string
                    duration_hours: number
                    status: 'pending' | 'accepted' | 'completed' | 'cancelled'
                    created_at: string
                    updated_at: string
                }
                Insert: {
                    id?: string
                    requester_id: string
                    caregiver_id: string
                    dog_id?: string | null
                    title: string
                    description?: string | null
                    care_type: 'walk' | 'sitting' | 'grooming' | 'hospital' | 'other'
                    datetime: string
                    duration_hours?: number
                    status?: 'pending' | 'accepted' | 'completed' | 'cancelled'
                    created_at?: string
                    updated_at?: string
                }
                Update: {
                    id?: string
                    requester_id?: string
                    caregiver_id?: string
                    dog_id?: string | null
                    title?: string
                    description?: string | null
                    care_type?: 'walk' | 'sitting' | 'grooming' | 'hospital' | 'other'
                    datetime?: string
                    duration_hours?: number
                    status?: 'pending' | 'accepted' | 'completed' | 'cancelled'
                    created_at?: string
                    updated_at?: string
                }
            }
            family_groups: {
                Row: {
                    id: string
                    name: string
                    creator_id: string
                    dog_ids: string[]
                    created_at: string
                }
                Insert: {
                    id?: string
                    name: string
                    creator_id: string
                    dog_ids?: string[]
                    created_at?: string
                }
                Update: {
                    id?: string
                    name?: string
                    creator_id?: string
                    dog_ids?: string[]
                    created_at?: string
                }
            }
            family_members: {
                Row: {
                    group_id: string
                    member_id: string
                    role: 'owner' | 'admin' | 'member'
                    joined_at: string
                }
                Insert: {
                    group_id: string
                    member_id: string
                    role?: 'owner' | 'admin' | 'member'
                    joined_at?: string
                }
                Update: {
                    group_id?: string
                    member_id?: string
                    role?: 'owner' | 'admin' | 'member'
                    joined_at?: string
                }
            }
            mode_unlocks: {
                Row: {
                    id: string
                    guardian_id: string
                    mode: 'basic' | 'care' | 'family'
                    unlocked_at: string
                    criteria_met_json: Json
                }
                Insert: {
                    id?: string
                    guardian_id: string
                    mode: 'basic' | 'care' | 'family'
                    unlocked_at?: string
                    criteria_met_json: Json
                }
                Update: {
                    id?: string
                    guardian_id?: string
                    mode?: 'basic' | 'care' | 'family'
                    unlocked_at?: string
                    criteria_met_json?: Json
                }
            }
        }
        Views: {
            [_ in never]: never
        }
        Functions: {
            [_ in never]: never
        }
        Enums: {
            user_role: 'user' | 'admin'
            match_status: 'pending' | 'accepted' | 'rejected'
            schedule_status: 'proposed' | 'confirmed' | 'completed' | 'cancelled'
            chat_room_type: 'direct' | 'group'
            message_type: 'text' | 'image' | 'schedule' | 'system'
            dog_gender: 'male' | 'female'
            badge_type: 'verified' | 'active_walker' | 'top_reviewer' | 'care_angel'
            mode_type: 'basic' | 'care' | 'family'
            care_type: 'walk' | 'sitting' | 'grooming' | 'hospital' | 'other'
            care_status: 'pending' | 'accepted' | 'completed' | 'cancelled'
            family_role: 'owner' | 'admin' | 'member'
        }
        CompositeTypes: {
            [_ in never]: never
        }
    }
}
